In [ ]:
import numpy as np

In [ ]:
a =  np.array([1, 3, 4, 5])
a

array([1, 3, 4, 5])

In [ ]:
a= np.array([ [1, 2, 3], [2, 4, 6], [9,10, 11] ])
a

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 9, 10, 11]])

In [ ]:
a.ndim

2

In [ ]:
a.itemsize

8

In [ ]:
a.shape

(3, 3)

In [ ]:
b= np.array([ [1, 2, 3], [2, 4, 6], [9,10, 11] ], dtype=np.float64)
print(b)

[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 9. 10. 11.]]


In [ ]:
# array feeler

a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c = np.full((4, 5), 30)
c

array([[30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30]])

In [ ]:
c = np.linspace(1, 5, 50)
c

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
x = np.arange(1, 9)
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
p = np.array([ [1, 2, 3], [2, 4, 6] ])
p.reshape(3,2)

array([[1, 2],
       [3, 2],
       [4, 6]])

In [ ]:
#math operations
a = np.arange(2, 22).reshape(2, 10)
b = np.arange(0, 30).reshape(3, 10)

In [ ]:
a

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21]])

In [ ]:
a.max()

21

In [ ]:
a.sum(axis=1)

array([ 65, 165])

In [ ]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
        2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569]])

In [ ]:
# slicing
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
t = b[2, 5]
t

25

In [ ]:
b[:, 4:]

array([[ 4,  5,  6,  7,  8,  9],
       [14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a = np.arange(6, 12).reshape(3, 2)
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
#looping
for row in a.flat:
  print(row)

6
7
8
9
10
11


In [ ]:
a = np.arange(0, 12).reshape(3, 4)
b = np.arange(12, 24).reshape(3, 4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c = np.vstack((a, b))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c = np.hstack((a, b))
c

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# split
a = np.arange(0, 60).reshape(6, 10)
b = np.arange(12, 24).reshape(3, 4)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
result =  np.hsplit(a, 2)

In [ ]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [55, 56, 57, 58, 59]])

In [ ]:
a = np.arange(0, 60).reshape(6, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
b =  (a < 20)

In [ ]:
a[b] = -1

In [ ]:
a

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
a = np.arange(6, 12).reshape(3, 2)
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
for x in np.nditer(a, order='K', op_flags=['readwrite']):
  x[...] = x*x
  print(x)

1296
2401
4096
6561
10000
14641


In [ ]:
a = np.arange(6, 12).reshape(3, 2)
b = np.arange(0, 6).reshape(3, 2)

In [ ]:
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
for x, y in np.nditer([a,b]):
  print(x, y)

6 0
7 1
8 2
9 3
10 4
11 5
